services:
  fabrica-sabor_cia:
    container_name: fabrica-sabor_cia
    build:
      context: .
      dockerfile: Dockerfile
    image: fabrica-sabor_cia:latest
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    expose:
      - ${PORT}
    networks:
      - fabrica-network

networks:
  fabrica-network:
    external: true
